
jira:
  password: {cipher}ebbfb1f30e522defefb15c31fd983e134adba0839b07b4101459ef4c7222685a

---

spring:
  profiles: prod
jira:
  password: HelloWord123-prod

---


spring:
  profiles: dev
jira:
  password: HelloWord123-dev
